packages:
  - apps/*
  - packages/*
  - crates/tauri-plugin-*
  - infra
  - scripts/orgIdBackfill
peerDependencyRules:
  allowedVersions:
    next-auth>next: '>=16.0.0'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - aws-sdk
  - cbor-extract
  - esbuild
  - ffmpeg-static
  - msgpackr-extract
  - node-av
  - protobufjs
  - sharp
  - unrs-resolver
  - workerd
